apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-app
  namespace: default
  labels:
    app: fb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-app
  template:
    metadata:
      labels:
        app: fb-app
    spec:
      containers:
      - name: fb-app
        # REPLACE THIS with your actual Docker Hub username and image
        image: shubhamgote/fb-app:latest 
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
